version: '2'

services:
  source:
    image: busybox
    container_name: 'dpl-src'
    volumes:
      - $PWD:/taller/dpl-8

  database:
    image: mysql:5.6
    container_name: 'dpl-db'
    hostname: "database"
    environment:
      - MYSQL_USER=dpl
      - MYSQL_DATABASE=drupal_dpl
      - MYSQL_PASSWORD=SenhaDPL
      - MYSQL_ROOT_PASSWORD=drupal_dpl

  dev:
    image: drupal-8-tests
    build: ./docker
    hostname: "dev"
    working_dir: /taller/dpl-8
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    links:
      - database
    volumes_from:
      - source
    volumes:
      - $HOME/.ssh:/taller/.ssh
      - $HOME/.gitconfig:/taller/.gitconfig
